baseURL = 'https://meze0.top/'
languageCode = 'zh-cn'
title = "Meze's Blog"
theme = 'hugo-theme-reimu'

defaultContentLanguage = 'zh-cn'

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup.highlight]
guessSyntax = true
noClasses = false

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.injector]
  head_end = '<link rel="stylesheet" href="/css/custom.css">'
